name: washit_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  dotted_line: ^3.2.2
  get: 4.6.6
  google_fonts: any
  iconsax: ^0.0.8
  fl_chart: ^0.69.0
  http: ^1.2.2
  image_picker: ^1.1.2
  get_storage: any
  shimmer: ^3.0.0
  intl: ^0.19.0
  slider_button: ^2.1.0
  device_info_plus: ^9.1.2
  flutter_rating_bar: ^4.0.1

  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  #  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img_home/
    - assets/img_user/avatar1.jpg
